---
- name: install iio-sensor-proxy
  become: true
  apt:
    name: iio-sensor-proxy

- name: captive portal script
  copy:
    dest: ~/.local/bin/gateway
    mode: 0700
    content: |
      #!/bin/bash
      xdg-open http://$(ip -o route | grep default | awk '{print $3}')
