---
  - name: remove unnecessary packages
    become: true
    apt:
      name: "{{ packages }}"
      state: absent
      purge: true
      autoremove: true
    vars:
      packages:
        - thunderbird
        - hypnotix
