---
- name: install flatpak
  become: true
  apt:
    name: flatpak

- name: flathub repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
