---
- name: install docker prereqs
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg

- name: docker apt key
  become: true
  shell:
    cmd: curl https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker-archive-keyring.pgp
    creates: /etc/apt/keyrings/docker-archive-keyring.pgp

- name: docker apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-archive-keyring.pgp] https://download.docker.com/linux/debian {{ debian_codename }} stable
    state: present
    filename: docker

- name: install docker packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin

- name: ensure docker group exists
  become: true
  group:
    name: docker

- name: add my user to docker group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: start docker service
  become: true
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: start containerd service
  become: true
  ansible.builtin.service:
    name: containerd
    enabled: yes
    state: started
