---
  - name: install base packages
    become: true
    apt:
      name: "{{ packages }}"
      update_cache: true
    vars:
      packages:
        - vim
        - git
        - htop
        - jq
        - curl
        - gpg
        - apt-transport-https
        - fish
        - flatpak

  - name: make .ssh folder
    ansible.builtin.file:
      path: ~/.ssh
      state: directory

  - name: create keypair
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_ed25519
      type: ed25519
      comment: "{{ ansible_facts['nodename'] }}"
