---
  - name: install hack fonts
    become: true
    apt:
      name: fonts-hack

  - name: update font cache
    command:
      cmd: fc-cache -rf

  - name: set hack as default monospace font
    community.general.dconf:
      key: /org/gnome/desktop/interface/monospace-font-name
      value: "'Hack 10'"
